---
title: "Articles"
---
1. [Atkinson, D. (2022). Geometry in medical imaging: DICOM and NIfTI formats.](atkinson_2022_dcmnii.pdf)
1. [Bidgood WD Jr, Horii SC, Prior FW, Van Syckle DE. Understanding and using DICOM, the data interchange standard for biomedical imaging. J Am Med Inform Assoc. 1997 May-Jun;4(3):199-212. doi: 10.1136/jamia.1997.0040199. PMID: 9147339; PMCID: PMC61235.](bidgood_1997_dicom.pdf)
1. [Glen, D. R., Taylor, P. A., Buchsbaum, B. R., Cox, R. W., & Reynolds, R. C. (2020). Beware (surprisingly common) left-right flips in your MRI data: an efficient and robust method to check MRI dataset consistency using AFNI. Frontiers in neuroinformatics, 14, 18.](glen_LRflip_2020.pdf)
1. [Larobina, M., & Murino, L. (2014). Medical image file formats. Journal of digital imaging, 27(2), 200-206.](larobina_2014_formats.pdf)
1. [Li, X., Morgan, P. S., Ashburner, J., Smith, J., & Rorden, C. (2016). The first step for neuroimaging data analysis: DICOM to NIfTI conversion. Journal of neuroscience methods, 264, 47-56.](li_2016_nifti.pdf)