---
title: "Modules"
execute:
  freeze: auto
---

<!--
- Anatomical - signal source, image type utility (anatomy, parcellate, volume)
- Software install - dcm2niix, FSL, AFNI, FreeSurfer
- DICOM - structure, interacting, source
- NIfTI - structure, creating, interacting (mango, afni, fsl)
- BIDS - description, structure, validation
- Inhomogeneity - signal distribution (and source), intensity vs anatomy, correcting
- Brain extraction - bet, 3dskullstrip, ants
- Tissue segmentation - ants
- Transformation - rigid, affine, diffeomorphic, templates and atlases (Talairach, MNI)
- Parcellation
- ANTs - registration based segmentation, template construction
- FreeSurfer - pipeline, prep, execution, output files
- fMRIPrep - https://fmriprep.org/en/stable/workflows.html#preprocessing-of-structural-mri
-->

<!-- TODO:
- Add image type utility (anatomy, parcellate, volume)
- add prep material (read article before class)
-->


<details>

<summary> Module 1: Signal and Files </summary>

| Date | Topic | Slides | Materials | Exercises |
|--------|---------------|--------|--------|---------|------|-----------|
| TBD | 1. Magnetic Resonance Imaging | [Slides](../lectures/mri_overview/mri_overview.qmd){target="_blank"} | [Articles](../lectures/mri_overview/articles/articles.qmd){target="_blank"} | |
| TBD | 2. T1-weighted signal | [Slides](../lectures/t1w_signal/t1w_signal.qmd){target="_blank"} | | |
| TBD | 3. MRI Data Formats | [Slides](../lectures/dicom/dicom.qmd){target="_blank"} | [Articles](../lectures/dicom/articles/articles.qmd){target="_blank"} | Practice |
| TBD | 4. BIDS | [Slides](../lectures/bids/bids.qmd){target="_blank"} | Code | Practice |

</details>


<details>

<summary> Module 2: Pipeline Steps </summary>

| Date | Topic | Slides | Materials | Exercises |
|--------|---------------|--------|--------|---------|------|-----------|
| TBD | 1. Bias correction | Slides | Code | Practice |
| TBD | 2. Brain extraction | Slides | Code | Practice |
| TBD | 3. Tissue segmentation | Slides | Code | Practice |
| TBD | 4. Transformation | Slides | Code | Practice |

</details>


<details>

<summary> Module 3: Software Packages </summary>

| Date | Topic | Slides | Materials | Exercises |
|--------|---------------|--------|--------|---------|------|-----------|
| TBD | 1. ITK-snap | Slides | Code | Practice |
| TBD | 2. ANTs | Slides | Code | Practice |
| TBD | 3. FreeSurfer | Slides | Code | Practice |
| TBD | 4. fMRIPrep | Slides | Code | Practice |

</details>


<!-- - Software
- Resources
- Data -->
