---
title: "T1-Weighted Signal"
author: Nathan M. Muncy
date: today
format:
  revealjs:
    footer: "MRI: T1w"
    logo: ../../media/nd_logo.png
    transition: slide
    slide-number: true
engine: knitr
---


## MRI data types

<!-- https://radiopaedia.org/articles/mri-sequences-overview?lang=us -->
T1w
T2w
PD
MRS
Perfusion
Flair
DWI
SWI
fMRI


## Protocols and contrast

Calibrated protocol for tissue differences
Contrast
- Protons
- Diffusion
- Hb, dOHb
Underlay - dynamics in field


## Precession

Spin
Magnetic Alignment
Larmor frequency
Gradient


## Excitation
Radiofrequency Pulse
Resonant Frequency
Low -> High Energy
Phase Alignment
Bo and Mo




## Signal - Transverse Plane

Rotating B1 - induce current - MRI signal

## Longitudinal recovery
## Timescale (T1w)
## Rates of recovery
## Tissue contrast
## Gray and white matter


Proton align to Bo - Mz
Known precession
Resonant RF Pulse
High energy state
Phase alignment
Oscillating signal in B1, Mxy
T2 decay (dephase), decrease Mxy
Tissue type in T2 decay (water slow, fat middle, muscle fast)
180 Pulse - invert dephase -> rephase
(Frequency encoding gradient, phase encoding gradient)
Signal from fat (high), water (low)